import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/authProvider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/context/reactQueryProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-sans bg-black", fontSans.variable)}>
        <ReactQueryProvider>
          <AuthProvider>
            <main className="max-w-5xl m-auto relative">{children}</main>
            <Toaster />
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
