export const CATEGORY_COLOR_COUNT = 20;

export const TEXT_COLORS = {
  category1: "text-category1",
  category2: "text-category2",
  category3: "text-category3",
  category4: "text-category4",
  category5: "text-category5",
  category6: "text-category6",
  category7: "text-category7",
  category8: "text-category8",
  category9: "text-category9",
  category10: "text-category10",
  category11: "text-category11",
  category12: "text-category12",
  category13: "text-category13",
  category14: "text-category14",
  category15: "text-category15",
  category16: "text-category16",
  category17: "text-category17",
  category18: "text-category18",
  category19: "text-category19",
  category20: "text-category20",
};

export const BG_COLORS = {
  category1: "bg-category1",
  category2: "bg-category2",
  category3: "bg-category3",
  category4: "bg-category4",
  category5: "bg-category5",
  category6: "bg-category6",
  category7: "bg-category7",
  category8: "bg-category8",
  category9: "bg-category9",
  category10: "bg-category10",
  category11: "bg-category11",
  category12: "bg-category12",
  category13: "bg-category13",
  category14: "bg-category14",
  category15: "bg-category15",
  category16: "bg-category16",
  category17: "bg-category17",
  category18: "bg-category18",
  category19: "bg-category19",
  category20: "bg-category20",
};
